#!/bin/bash

MKDRUMCOMMAND="./makedrum"

for d in *_marches strathspeys standards jigs airs hornpipes other
do
	for f in $d/*.ly $d/*/*.ly
	do
		if [ ! -f $f ] ; then
			continue
		fi
		$MKDRUMCOMMAND $f
	done;
done;
