#!/bin/bash

SHELLCMD='sh'
PYTHONCMD='python3.4'
LATEXCMD='pdflatex'

#$SHELLCMD load_scores

#$PYTHONCMD makebook -o tex/main_full.tex full
#$PYTHONCMD makebook -o tex/main_drums.tex drums
#$PYTHONCMD makebook -o tex/main_pipes.tex pipes
#$PYTHONCMD makebook -o tex/main_bass.tex bass
#$PYTHONCMD makebook -o tex/main_tenor.tex tenor
#$PYTHONCMD makebook -o tex/main_side.tex side snare

for ins in tenor;
do
	printf "\\documentclass{tex/score_book}

 \\title{Seaforth Highlanders of Holland\\\\ %s Scores}
 \\author{Eric Teunis de Boone}

\\begin{document}

\\input{./tex/titlepage.tex}

\\newpage
\\cleardoublepage
\\phantomsection
\\addcontentsline{toc}{section}{\contentsname}
\\begin{multicols}{2}
  \\tableofcontents
\\end{multicols}

%\\newpage
%\\input{./tex/playlist}
\\newpage
\\input{./tex/main_%s.tex}
\\end{document}
" "$instr" "$instr"
done;

echo "All setup!"

#read -p "Press [Enter] to compile *.tex"

#for f in ./*.tex;
#do
#	$LATEXCMD $f
#done;
